name: Vercel Production Deployment

on:
  push:
    branches:
      - develop

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile

      - run: |
          pnpm run build
          pnpm --filter web run build

      - run: pnpm add -g vercel@latest

      - run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - run: vercel deploy --prebuilt --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
